// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: pkg/pb/employee.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortField int32

const (
	SortField_NAME     SortField = 0
	SortField_BIRTHDAY SortField = 1
	SortField_SALARY   SortField = 2
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "NAME",
		1: "BIRTHDAY",
		2: "SALARY",
	}
	SortField_value = map[string]int32{
		"NAME":     0,
		"BIRTHDAY": 1,
		"SALARY":   2,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_employee_proto_enumTypes[0].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_pkg_pb_employee_proto_enumTypes[0]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{0}
}

type AddEmployeeBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthday *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Salary   float64                `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary,omitempty"`
}

func (x *AddEmployeeBody) Reset() {
	*x = AddEmployeeBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmployeeBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmployeeBody) ProtoMessage() {}

func (x *AddEmployeeBody) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmployeeBody.ProtoReflect.Descriptor instead.
func (*AddEmployeeBody) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{0}
}

func (x *AddEmployeeBody) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddEmployeeBody) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *AddEmployeeBody) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

type Employee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birthday *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Salary   float64                `protobuf:"fixed64,4,opt,name=salary,proto3" json:"salary,omitempty"`
}

func (x *Employee) Reset() {
	*x = Employee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{1}
}

func (x *Employee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *Employee) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

type AddEmployeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employee *AddEmployeeBody `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
}

func (x *AddEmployeeRequest) Reset() {
	*x = AddEmployeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmployeeRequest) ProtoMessage() {}

func (x *AddEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmployeeRequest.ProtoReflect.Descriptor instead.
func (*AddEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{2}
}

func (x *AddEmployeeRequest) GetEmployee() *AddEmployeeBody {
	if x != nil {
		return x.Employee
	}
	return nil
}

type AddEmployeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddEmployeeResponse) Reset() {
	*x = AddEmployeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmployeeResponse) ProtoMessage() {}

func (x *AddEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmployeeResponse.ProtoReflect.Descriptor instead.
func (*AddEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{3}
}

func (x *AddEmployeeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddEmployeeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddEmployeeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveEmployeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveEmployeeRequest) Reset() {
	*x = RemoveEmployeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEmployeeRequest) ProtoMessage() {}

func (x *RemoveEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEmployeeRequest.ProtoReflect.Descriptor instead.
func (*RemoveEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveEmployeeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveEmployeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RemoveEmployeeResponse) Reset() {
	*x = RemoveEmployeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEmployeeResponse) ProtoMessage() {}

func (x *RemoveEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEmployeeResponse.ProtoReflect.Descriptor instead.
func (*RemoveEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveEmployeeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemoveEmployeeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Duration in seconds
type LongOpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration int64 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *LongOpRequest) Reset() {
	*x = LongOpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongOpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongOpRequest) ProtoMessage() {}

func (x *LongOpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongOpRequest.ProtoReflect.Descriptor instead.
func (*LongOpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{6}
}

func (x *LongOpRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type LongOpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok int64 `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *LongOpResponse) Reset() {
	*x = LongOpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongOpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongOpResponse) ProtoMessage() {}

func (x *LongOpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongOpResponse.ProtoReflect.Descriptor instead.
func (*LongOpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{7}
}

func (x *LongOpResponse) GetOk() int64 {
	if x != nil {
		return x.Ok
	}
	return 0
}

type SortByRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortField SortField `protobuf:"varint,1,opt,name=sortField,proto3,enum=employee.SortField" json:"sortField,omitempty"`
}

func (x *SortByRequest) Reset() {
	*x = SortByRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortByRequest) ProtoMessage() {}

func (x *SortByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortByRequest.ProtoReflect.Descriptor instead.
func (*SortByRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{8}
}

func (x *SortByRequest) GetSortField() SortField {
	if x != nil {
		return x.SortField
	}
	return SortField_NAME
}

type SortByResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employees []*Employee `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
}

func (x *SortByResponse) Reset() {
	*x = SortByResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortByResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortByResponse) ProtoMessage() {}

func (x *SortByResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortByResponse.ProtoReflect.Descriptor instead.
func (*SortByResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{9}
}

func (x *SortByResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

type AvgMedianSalaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AvgMedianSalaryRequest) Reset() {
	*x = AvgMedianSalaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgMedianSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgMedianSalaryRequest) ProtoMessage() {}

func (x *AvgMedianSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgMedianSalaryRequest.ProtoReflect.Descriptor instead.
func (*AvgMedianSalaryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{10}
}

type AvgMedianSalaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvgSalary    float64 `protobuf:"fixed64,1,opt,name=avgSalary,proto3" json:"avgSalary,omitempty"`
	MedianSalary float64 `protobuf:"fixed64,2,opt,name=medianSalary,proto3" json:"medianSalary,omitempty"`
}

func (x *AvgMedianSalaryResponse) Reset() {
	*x = AvgMedianSalaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_employee_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgMedianSalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgMedianSalaryResponse) ProtoMessage() {}

func (x *AvgMedianSalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_employee_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgMedianSalaryResponse.ProtoReflect.Descriptor instead.
func (*AvgMedianSalaryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_employee_proto_rawDescGZIP(), []int{11}
}

func (x *AvgMedianSalaryResponse) GetAvgSalary() float64 {
	if x != nil {
		return x.AvgSalary
	}
	return 0
}

func (x *AvgMedianSalaryResponse) GetMedianSalary() float64 {
	if x != nil {
		return x.MedianSalary
	}
	return 0
}

var File_pkg_pb_employee_proto protoreflect.FileDescriptor

var file_pkg_pb_employee_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x22, 0x7e, 0x0a, 0x08, 0x45, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x22, 0x4b, 0x0a, 0x12, 0x41, 0x64, 0x64,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x35, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x53, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x27, 0x0a, 0x15, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x0d,
	0x4c, 0x6f, 0x6e, 0x67, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x0e, 0x4c, 0x6f, 0x6e,
	0x67, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x42, 0x0a, 0x0d, 0x53,
	0x6f, 0x72, 0x74, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09,
	0x73, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22,
	0x42, 0x0a, 0x0e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x41, 0x76, 0x67, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5b, 0x0a,
	0x17, 0x41, 0x76, 0x67, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x67, 0x53,
	0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x61, 0x76, 0x67,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x6e, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x2a, 0x2f, 0x0a, 0x09, 0x53, 0x6f,
	0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x4d, 0x45, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x49, 0x52, 0x54, 0x48, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x41, 0x4c, 0x41, 0x52, 0x59, 0x10, 0x02, 0x32, 0x8e, 0x03, 0x0a, 0x0f,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4c, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x1c,
	0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a,
	0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12,
	0x1f, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x4c, 0x6f, 0x6e, 0x67, 0x4f, 0x70, 0x12, 0x17,
	0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x4f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x12, 0x17, 0x2e,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x41, 0x76, 0x67, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x53,
	0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x20, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x2e, 0x41, 0x76, 0x67, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x2e, 0x41, 0x76, 0x67, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_employee_proto_rawDescOnce sync.Once
	file_pkg_pb_employee_proto_rawDescData = file_pkg_pb_employee_proto_rawDesc
)

func file_pkg_pb_employee_proto_rawDescGZIP() []byte {
	file_pkg_pb_employee_proto_rawDescOnce.Do(func() {
		file_pkg_pb_employee_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_employee_proto_rawDescData)
	})
	return file_pkg_pb_employee_proto_rawDescData
}

var file_pkg_pb_employee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_pb_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_pb_employee_proto_goTypes = []interface{}{
	(SortField)(0),                  // 0: employee.SortField
	(*AddEmployeeBody)(nil),         // 1: employee.AddEmployeeBody
	(*Employee)(nil),                // 2: employee.Employee
	(*AddEmployeeRequest)(nil),      // 3: employee.AddEmployeeRequest
	(*AddEmployeeResponse)(nil),     // 4: employee.AddEmployeeResponse
	(*RemoveEmployeeRequest)(nil),   // 5: employee.RemoveEmployeeRequest
	(*RemoveEmployeeResponse)(nil),  // 6: employee.RemoveEmployeeResponse
	(*LongOpRequest)(nil),           // 7: employee.LongOpRequest
	(*LongOpResponse)(nil),          // 8: employee.LongOpResponse
	(*SortByRequest)(nil),           // 9: employee.SortByRequest
	(*SortByResponse)(nil),          // 10: employee.SortByResponse
	(*AvgMedianSalaryRequest)(nil),  // 11: employee.AvgMedianSalaryRequest
	(*AvgMedianSalaryResponse)(nil), // 12: employee.AvgMedianSalaryResponse
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
}
var file_pkg_pb_employee_proto_depIdxs = []int32{
	13, // 0: employee.AddEmployeeBody.birthday:type_name -> google.protobuf.Timestamp
	13, // 1: employee.Employee.birthday:type_name -> google.protobuf.Timestamp
	1,  // 2: employee.AddEmployeeRequest.employee:type_name -> employee.AddEmployeeBody
	0,  // 3: employee.SortByRequest.sortField:type_name -> employee.SortField
	2,  // 4: employee.SortByResponse.employees:type_name -> employee.Employee
	3,  // 5: employee.EmployeeService.AddEmployee:input_type -> employee.AddEmployeeRequest
	5,  // 6: employee.EmployeeService.RemoveEmployee:input_type -> employee.RemoveEmployeeRequest
	7,  // 7: employee.EmployeeService.LongOp:input_type -> employee.LongOpRequest
	9,  // 8: employee.EmployeeService.SortBy:input_type -> employee.SortByRequest
	11, // 9: employee.EmployeeService.AvgMedianSalary:input_type -> employee.AvgMedianSalaryRequest
	4,  // 10: employee.EmployeeService.AddEmployee:output_type -> employee.AddEmployeeResponse
	6,  // 11: employee.EmployeeService.RemoveEmployee:output_type -> employee.RemoveEmployeeResponse
	8,  // 12: employee.EmployeeService.LongOp:output_type -> employee.LongOpResponse
	10, // 13: employee.EmployeeService.SortBy:output_type -> employee.SortByResponse
	12, // 14: employee.EmployeeService.AvgMedianSalary:output_type -> employee.AvgMedianSalaryResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_pb_employee_proto_init() }
func file_pkg_pb_employee_proto_init() {
	if File_pkg_pb_employee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_employee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmployeeBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmployeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEmployeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveEmployeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveEmployeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongOpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongOpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortByRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortByResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvgMedianSalaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_employee_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvgMedianSalaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_employee_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_employee_proto_goTypes,
		DependencyIndexes: file_pkg_pb_employee_proto_depIdxs,
		EnumInfos:         file_pkg_pb_employee_proto_enumTypes,
		MessageInfos:      file_pkg_pb_employee_proto_msgTypes,
	}.Build()
	File_pkg_pb_employee_proto = out.File
	file_pkg_pb_employee_proto_rawDesc = nil
	file_pkg_pb_employee_proto_goTypes = nil
	file_pkg_pb_employee_proto_depIdxs = nil
}
